name: Build

on: [push, pull_request]

jobs:
  build:
    # Skip if pushing to master because then other workflow will run
    if: ${{ (github.event_name == 'push' && github.ref != 'refs/heads/master') || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Build Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # Skips root build script (so no `yarn run build` is run)
          skip_build: true
          # Runs `vue-cli-service electron:build`
          use_vue_cli: true

          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}
          release: false
